# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMaKgLMmtrrKkNoQx4dD4ybKk6S1iqc5
"""

nombre = ""
Apellido = ""
cargo = ""
sueldo_bruto = 0
mesero = ""
lista_trabajadores = [" "," "]
lista_trabajadores1 = []
lista_trabajadores2 = []
lista_trabajadores3 = []
lista_mesero = [mesero]
lista_cocinero = []
lista_cajero = []
descuento = ""
respuesta = 0
items = 0
AFP = 0
Salud = 0

while True:
  print('''
  1) Registrar Trabajador
  2) Lista De Los Trabajadores
  3) Sueldos Por Cargo
  4) Salir
  ''')

  respuesta = int(input())
  if respuesta == 1:
    lista_trabajadores = input("Nombre: ")
    lista_trabajadores1 = input("Apellido: ")
    lista_trabajadores2 = input("Cargo (Mesero, Cocinero, Cajero): ")
    lista_trabajadores3 = int(input("Cual Es Su Sueldo Bruto: "))
    respuesta = int(input("Que tipo de salud tienes? (1. Salud / 2. AFP): "))
    if respuesta == 1:
      print("se genero un descuento del 7%")
    elif respuesta == 2:
      print("Se genero un descuento del 10%")

  elif respuesta == 2:
    print(lista_trabajadores)
    print(lista_trabajadores1)
    print(lista_trabajadores2)
    print(lista_trabajadores3)

  elif respuesta == 3:
    input("Selecciona tu cargo (Mesero, Cocinero, Cajero): ")
    if respuesta == mesero:
      print(f"mesero {mesero[1]}")

  elif respuesta == 4:
    break